// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TagService.Infrastructure.Data;

#nullable disable

namespace TagService.Infrastructure.Migrations
{
    [DbContext(typeof(TagServiceDbContext))]
    [Migration("20250718124307_AddNewFields")]
    partial class AddNewFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TagService.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountQuestion")
                        .HasColumnType("integer");

                    b.Property<int>("CountWotchers")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyRequestCount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeeklyRequestCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountQuestion = 0,
                            CountWotchers = 0,
                            CreatedAt = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRequestCount = 0,
                            Description = "Язык C#",
                            Name = "csharp",
                            WeeklyRequestCount = 0
                        },
                        new
                        {
                            Id = 2,
                            CountQuestion = 0,
                            CountWotchers = 0,
                            CreatedAt = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRequestCount = 0,
                            Description = "ASP.NET Core 9",
                            Name = "asp.net-core",
                            WeeklyRequestCount = 0
                        },
                        new
                        {
                            Id = 3,
                            CountQuestion = 0,
                            CountWotchers = 0,
                            CreatedAt = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRequestCount = 0,
                            Description = "Entity Framework Core",
                            Name = "entity-framework",
                            WeeklyRequestCount = 0
                        },
                        new
                        {
                            Id = 4,
                            CountQuestion = 0,
                            CountWotchers = 0,
                            CreatedAt = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRequestCount = 0,
                            Description = "LINQ‑выражения",
                            Name = "linq",
                            WeeklyRequestCount = 0
                        },
                        new
                        {
                            Id = 5,
                            CountQuestion = 0,
                            CountWotchers = 0,
                            CreatedAt = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRequestCount = 0,
                            Description = "SQL‑запросы",
                            Name = "sql",
                            WeeklyRequestCount = 0
                        },
                        new
                        {
                            Id = 6,
                            CountQuestion = 0,
                            CountWotchers = 0,
                            CreatedAt = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRequestCount = 0,
                            Description = "PostgreSQL",
                            Name = "postgresql",
                            WeeklyRequestCount = 0
                        },
                        new
                        {
                            Id = 7,
                            CountQuestion = 0,
                            CountWotchers = 0,
                            CreatedAt = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRequestCount = 0,
                            Description = "Контейнеризация",
                            Name = "docker",
                            WeeklyRequestCount = 0
                        },
                        new
                        {
                            Id = 8,
                            CountQuestion = 0,
                            CountWotchers = 0,
                            CreatedAt = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRequestCount = 0,
                            Description = "Очереди RabbitMQ",
                            Name = "rabbitmq",
                            WeeklyRequestCount = 0
                        },
                        new
                        {
                            Id = 9,
                            CountQuestion = 0,
                            CountWotchers = 0,
                            CreatedAt = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRequestCount = 0,
                            Description = "REST‑API",
                            Name = "rest",
                            WeeklyRequestCount = 0
                        },
                        new
                        {
                            Id = 10,
                            CountQuestion = 0,
                            CountWotchers = 0,
                            CreatedAt = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DailyRequestCount = 0,
                            Description = "Микросервисная арх‑ра",
                            Name = "microservices",
                            WeeklyRequestCount = 0
                        });
                });

            modelBuilder.Entity("TagService.Domain.Entities.UserTagParticipation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnswersWritten")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuestionsCreated")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("UserTagParticipations");
                });

            modelBuilder.Entity("TagService.Domain.Entities.WatchedTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("WatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("WatchedTags");
                });

            modelBuilder.Entity("TagService.Domain.Entities.UserTagParticipation", b =>
                {
                    b.HasOne("TagService.Domain.Entities.Tag", "Tag")
                        .WithMany("UserTagParticipations")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TagService.Domain.Entities.WatchedTag", b =>
                {
                    b.HasOne("TagService.Domain.Entities.Tag", "Tag")
                        .WithMany("WatchedTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TagService.Domain.Entities.Tag", b =>
                {
                    b.Navigation("UserTagParticipations");

                    b.Navigation("WatchedTags");
                });
#pragma warning restore 612, 618
        }
    }
}
