FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ENV REACT_APP_API_BASE_URL=/api
RUN npm run build

FROM alpine AS export
RUN mkdir -p /dist
# CRA -> build, не dist
COPY --from=build /app/build /dist