# ---------- build stage ----------
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

# CRA читает REACT_APP_* во время сборки
ENV REACT_APP_API_BASE_URL=/api
RUN npm run build

# ---------- runtime stage ----------
FROM nginx:alpine
# наш конфиг nginx рядом с докерфайлом
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# У CRA артефакты в /app/build
COPY --from=build /app/build /usr/share/nginx/html